version: "3"

services:
  payment:
    container_name: Auth
    build:
      context: .
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      DATABASE_URL: jdbc:postgres://db_user:db_pass@postgres:5432/sopp
    depends_on:
      - postgres
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KP^FOz63OneNl{dH
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'