spring:
  application.name: Auth
  datasource:
    url: jdbc:postgresql://${database.endpoint}/${database.name}
    username: ${database.user}
    password: ${database.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
database:
  endpoint: ${ENDPOINT}
  name: ${NAME}
  user: ${USER}
  password: ${PASSWORD}
server:
  port: 8081
sopp:
  server:
    wallet:
      url: http://localhost:8082/wallet
